# Arion - AI Web3 Assistant NodeOps Template
version: 0.1

services:
  app:
    # Public Docker image
    image: nikhilraikwar/arion:latest
    
    # Always pull latest version
    imagePullPolicy: Always
    
    # No custom command needed
    command: []
    
    # No custom args needed
    args: []
    
    # Network configuration
    ports:
      - containerPort: 3000
        protocol: TCP
        expose: true
    
    # Environment variables for runtime
    # NOTE: Keep this YAML private on NodeOps if it contains API keys!
    env:
        - name: NODE_ENV
        value: production
      - name: NEXT_PUBLIC_PRIVY_APP_ID
        value: YOUR_PRIVY_APP_ID
      - name: NEXT_PUBLIC_ALCHEMY_API_KEY
        value: YOUR_ALCHEMY_API_KEY
      - name: AIML_API_KEY
        value: YOUR_AIML_API_KEY
      - name: ALCHEMY_API_KEY
        value: YOUR_ALCHEMY_API_KEY
      - name: ALCHEMY_API_URL
        value: https://eth-mainnet.g.alchemy.com/v2/YOUR_KEY
      - name: ALCHEMY_API_URL_ETH_MAINNET
        value: https://eth-mainnet.g.alchemy.com/v2/YOUR_KEY
      - name: ALCHEMY_API_URL_POLYGON_MAINNET
        value: https://polygon-mainnet.g.alchemy.com/v2/YOUR_KEY
      - name: ALCHEMY_API_URL_BASE_MAINNET
        value: https://base-mainnet.g.alchemy.com/v2/YOUR_KEY
      - name: ALCHEMY_API_URL_OPTIMISM_MAINNET
        value: https://opt-mainnet.g.alchemy.com/v2/YOUR_KEY
      - name: ALCHEMY_API_URL_ARBITRUM_MAINNET
        value: https://arb-mainnet.g.alchemy.com/v2/YOUR_KEY
    
    # Resource allocation
    resourceUsage:
      idle:
        cpu: 200    # 0.2 CPU cores
        memory: 400 # 400 MB RAM