# Arion - AI Web3 Assistant NodeOps Template
# Users will be prompted to provide their API keys when deploying
version: 0.1

services:
  app:
    image: nikhilraikwar/arion:latest
    imagePullPolicy: Always
    command: []
    args: []
    ports:
      - containerPort: 3000
        protocol: TCP
        expose: true
    env:
      - name: NODE_ENV
        value: production
      - name: NEXT_PUBLIC_PRIVY_APP_ID
        value: '{{.NEXT_PUBLIC_PRIVY_APP_ID}}'
      - name: NEXT_PUBLIC_ALCHEMY_API_KEY
        value: '{{.NEXT_PUBLIC_ALCHEMY_API_KEY}}'
      - name: AIML_API_KEY
        value: '{{.AIML_API_KEY}}'
      - name: ALCHEMY_API_KEY
        value: '{{.ALCHEMY_API_KEY}}'
      - name: ALCHEMY_API_URL
        value: https://eth-mainnet.g.alchemy.com/v2/{{.ALCHEMY_API_KEY}}
      - name: ALCHEMY_API_URL_ETH_MAINNET
        value: https://eth-mainnet.g.alchemy.com/v2/{{.ALCHEMY_API_KEY}}
      - name: ALCHEMY_API_URL_POLYGON_MAINNET
        value: https://polygon-mainnet.g.alchemy.com/v2/{{.ALCHEMY_API_KEY}}
      - name: ALCHEMY_API_URL_BASE_MAINNET
        value: https://base-mainnet.g.alchemy.com/v2/{{.ALCHEMY_API_KEY}}
      - name: ALCHEMY_API_URL_OPTIMISM_MAINNET
        value: https://opt-mainnet.g.alchemy.com/v2/{{.ALCHEMY_API_KEY}}
      - name: ALCHEMY_API_URL_ARBITRUM_MAINNET
        value: https://arb-mainnet.g.alchemy.com/v2/{{.ALCHEMY_API_KEY}}
    resourceUsage:
      idle:
        cpu: 200
        memory: 400
